

name: CI with Automated Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: CI with Automated Testing Step
      run: echo "CI with Automated Testing
